# Recipe for Pointcept - Point Cloud Perception Framework
# https://github.com/Pointcept/Pointcept

context:
  version: "1.6.0"

package:
  name: pointcept
  version: ${{ version }}

source:
  git: https://github.com/Pointcept/Pointcept.git
  tag: v${{ version }}
  patches:
    - patches/conda-pointops-cuda.patch

build:
  number: 0
  skip:
    - not linux
  variant:
    use_keys:
      - cuda_version
  script:
    env:
      TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6;8.9;9.0"
    content: |
      export CUDA_HOME=$PREFIX

      # Copy the pointcept module to site-packages
      mkdir -p $PREFIX/lib/python$PY_VER/site-packages/pointcept
      cp -r pointcept/* $PREFIX/lib/python$PY_VER/site-packages/pointcept/

      # Build and install pointops extension
      cd libs/pointops
      $PYTHON setup.py build_ext --inplace
      $PYTHON setup.py install --single-version-externally-managed --record=record.txt
      cd ../..

      # Copy configs and tools for convenience
      mkdir -p $PREFIX/share/pointcept
      cp -r configs $PREFIX/share/pointcept/
      cp -r tools $PREFIX/share/pointcept/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools >=41.0
    - wheel
    - pytorch-gpu >=2.6.0
    - numpy
    - cuda-version
    - cuda-cudart-dev
    - cuda-nvcc
    - libcusparse-dev
    - libcublas-dev
    - libcusolver-dev
  run:
    - ${{ pin_compatible('python', upper_bound='x.x') }}
    - pytorch-gpu >=2.6.0
    - torchvision
    - ${{ pin_compatible('cuda-version', lower_bound='x.x', upper_bound='x') }}
    - cuda-cudart
    - spconv
    - numpy
    - scipy
    - h5py
    - plyfile
    - pyyaml
    - addict
    - yapf
    - termcolor
    - timm
    - einops
    - sharedarray
    - tensorboard
    - tensorboardx
  ignore_run_exports:
    from_package:
      - cuda-cudart-dev
      - libcusparse-dev
      - libcublas-dev
      - libcusolver-dev
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - pointcept
      pip_check: false

about:
  homepage: https://github.com/Pointcept/Pointcept
  license: MIT
  license_file: LICENSE
  summary: Point Cloud Perception Framework for 3D understanding

extra:
  recipe-maintainers:
    - lllangWV
