# Recipe for xatlas - Python bindings for the xatlas UV unwrapping library
# https://github.com/mworchel/xatlas-python

context:
  version: "0.0.11"

package:
  name: xatlas
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/x/xatlas/xatlas-${{ version }}.tar.gz
  sha256: 72f0bc6c42c19252be87e947d9dfe251c8d6c6943fd43e3d173ddc6b1afad693

build:
  number: 0
  string: py${{ python | version_to_buildstring }}_${{ hash }}
  skip:
    - not linux
  script:
    content: |
      $PYTHON -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build-core >=0.10
    - pybind11
  run:
    - ${{ pin_compatible('python', upper_bound='x.x') }}

tests:
  - python:
      imports:
        - xatlas
      pip_check: true

about:
  homepage: https://github.com/mworchel/xatlas-python
  license: MIT
  license_file: LICENSE
  summary: Python bindings for the xatlas mesh parameterization / UV unwrapping library
  repository: https://github.com/mworchel/xatlas-python

extra:
  recipe-maintainers:
    - lllangWV
