# Recipe for ShapeR - 3D Shape Reconstruction from SLAM observations
# https://github.com/facebookresearch/ShapeR

context:
  version: "0.0.1"
  commit: "5cc03097f436c9e344ec5f9f7c6675987b1be3b9"
  torch_proc_type: ${{ "cuda" if cuda_compiler_version != "None" else "cpu" }}

package:
  name: shaper
  version: ${{ version }}

source:
  url: https://github.com/facebookresearch/ShapeR/archive/${{ commit }}.tar.gz
  sha256: b7f86028764eb8f10ab6273666a0e2d2f416c0501ff7fd63e184cf32f43f9281

build:
  number: 0
  string: cu${{ cuda_version | version_to_buildstring }}_py${{ python | version_to_buildstring }}_${{ hash }}
  skip:
    - not linux
  variant:
    use_keys:
      - cuda_version
  script: build.sh

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - wheel
    - cuda-version
  run:
    - ${{ pin_compatible('python', upper_bound='x.x') }}
    - pytorch * [build=${{ torch_proc_type }}*]
    - torchvision
    - torchaudio
    - ${{ pin_compatible('cuda-version', lower_bound='x.x', upper_bound='x') }}
    # Core
    - numpy
    - tqdm
    - hydra-core
    - omegaconf
    - matplotlib
    - opencv
    - imageio
    - easydict
    - munch
    - plyfile
    # ML / generation
    - transformers
    - trimesh
    - scikit-image
    - diffusers
    - gradio
    - peft
    - einops
    - flash-attn
    # Geometry / math
    - pymeshlab
    - sophuspy
    - fast-simplification
    - scikit-learn
    - timm
    - plotly
    - torchdiffeq
    - sentencepiece
    - protobuf
    - pyrender
    # Sparse operations
    - pytorch_cluster
    - torchsparse
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - shaper
        - shaper.model
        - shaper.dataset
      pip_check: false

about:
  homepage: https://github.com/facebookresearch/ShapeR
  license: CC-BY-NC-4.0
  license_file: LICENSE
  summary: "ShapeR: 3D Shape Reconstruction from SLAM observations using flow matching"
  repository: https://github.com/facebookresearch/ShapeR

extra:
  recipe-maintainers:
    - lllangWV
