# Recipe for cumm - CUDA Matrix Multiply library
# https://github.com/FindDefinition/cumm

context:
  version: "0.7.11"

package:
  name: cumm
  version: ${{ version }}

source:
  git: https://github.com/FindDefinition/cumm.git
  tag: v${{ version }}
  patches:
    - patches/conda-cuda-paths.patch

build:
  number: 0
  string: cu${{ cuda_version | version_to_buildstring }}_py${{ python | version_to_buildstring }}_${{ hash }}
  skip:
    - not linux
  variant:
    use_keys:
      - cuda_version
  script:
    env:
      CUMM_DISABLE_JIT: "1"
      CUMM_CUDA_VERSION: "${{ cuda_version }}"
      CUMM_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6;8.9;9.0"
    content: |
      export CUDA_HOME=$PREFIX
      $PYTHON -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools >=41.0
    - wheel
    - pccm >=0.4.15
    - ccimport >=0.4.4
    - pybind11 >=2.6.0
    - numpy
    - sympy
    - fire
    - cuda-version
    - cuda-cudart-dev
    - cuda-nvcc
    - libcublas-dev
    - libcurand-dev
    - cuda-nvrtc-dev
    - cuda-profiler-api
    - libcusparse-dev
  run:
    - ${{ pin_compatible('python', upper_bound='x.x') }}
    - pccm >=0.4.15
    - ccimport >=0.4.4
    - pybind11 >=2.6.0
    - numpy
    - sympy
    - fire
    - ${{ pin_compatible('cuda-version', lower_bound='x.x', upper_bound='x') }}
    - cuda-cudart
    - ${{ pin_compatible('cuda-nvrtc', lower_bound='x.x', upper_bound='x.x') }}
    - libcublas
    - libcurand
    - libcusparse
  ignore_run_exports:
    from_package:
      - cuda-cudart-dev
      - libcublas-dev
      - libcurand-dev
      - cuda-nvrtc-dev
      - libcusparse-dev
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - cumm
      # pip_check disabled: sympy's installed dist-info metadata (from
      # pyproject.toml) requires mpmath<1.4, but conda-forge's sympy recipe
      # only constrains mpmath>=0.19 — so conda installs mpmath 1.4 which
      # pip check flags as a conflict. PyPI/conda metadata mismatch.
      pip_check: false

about:
  homepage: https://github.com/FindDefinition/cumm
  license: Apache-2.0
  license_file: LICENSE
  summary: CUDA Matrix Multiply library with Python bindings

extra:
  recipe-maintainers:
    - lllangWV
