# Recipe for SAM 3D Objects - 3D object generation from Meta FAIR
# https://github.com/facebookresearch/sam-3d-objects

context:
  version: "0.0.1"

package:
  name: sam3d-objects
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script:
    content: |
      ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - pip
    - hatchling
    - hatch-requirements-txt
  run:
    - python >=3.12
    # Core
    - pytorch-gpu >=2.8.0,<2.10.0
    - torchvision
    - numpy
    - pillow
    - tqdm
    - loguru
    - scipy
    # Config / training
    - omegaconf
    - hydra-core
    - lightning
    - safetensors
    - optree
    - timm
    # 3D / geometry
    - pytorch3d
    - gsplat
    - open3d
    - trimesh
    - kaolin
    - plyfile
    - pyvista
    - pymeshfix
    - python-igraph
    # Visualization
    - matplotlib
    - plotly
    - seaborn
    - imageio
    - opencv
    # Attention backends
    - flash-attn
    # Mono depth / misc 3D
    - utils3d
    - xatlas-python
    - moge
    - pipeline
    # Misc
    - astor
    - easydict
    - huggingface_hub

tests:
  - script:
      - LIDRA_SKIP_INIT=1 ${{ PYTHON }} -c "import sam3d_objects"

about:
  homepage: https://github.com/facebookresearch/sam-3d-objects
  license: Apache-2.0
  license_file: LICENSE
  summary: SAM 3D Objects - 3D object generation from Meta FAIR
  repository: https://github.com/facebookresearch/sam-3d-objects

extra:
  recipe-maintainers:
    - lllangWV
