# Recipe for PyTorch3D - 3D deep learning library from Meta FAIR
# https://github.com/facebookresearch/pytorch3d

context:
  version: "0.7.9"

package:
  name: pytorch3d
  version: ${{ version }}

source:
  url: https://github.com/facebookresearch/pytorch3d/archive/v${{ version }}.tar.gz
  sha256: 96c1ef357c522e1f45b5f9c27bae9b75185034457ddbcacdd343a0ec50bc515f

build:
  number: 0
  skip:
    - not linux
  variant:
    use_keys:
      - cuda_version
  script:
    env:
      FORCE_CUDA: "1"
      TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6;8.9;9.0+PTX"
      MAX_JOBS: "${CPU_COUNT}"
    content: |
      $PYTHON -m pip install . -vv --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - ninja
    - numpy
    - pytorch-gpu >=2.8.0,<2.10.0
    - cuda-version
    - cuda-nvcc
    - cuda-cccl
    - cuda-cudart-dev
    - libcusparse-dev
    - libcusolver-dev
    - libcublas-dev
  run:
    - ${{ pin_compatible('python', upper_bound='x.x') }}
    - pytorch-gpu >=2.8.0,<2.10.0
    - ${{ pin_compatible('cuda-version', lower_bound='x.x', upper_bound='x') }}
    - cuda-cudart
    - iopath
    - fvcore
    - numpy
  ignore_run_exports:
    from_package:
      - cuda-cudart-dev
      - libcusparse-dev
      - libcusolver-dev
      - libcublas-dev
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - pytorch3d
        - pytorch3d.structures
        - pytorch3d.renderer
        - pytorch3d.ops
        - pytorch3d.loss
        - pytorch3d.io

about:
  homepage: https://github.com/facebookresearch/pytorch3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: PyTorch3D is FAIR's library of reusable components for deep learning with 3D data
  repository: https://github.com/facebookresearch/pytorch3d
  documentation: https://pytorch3d.org/

extra:
  recipe-maintainers:
    - lllangWV
