set -euxo pipefail

export QT_HOST_PATH="$PREFIX"

mkdir -p build
cd build

cmake ${SRC_DIR} ${CMAKE_ARGS} \
    -DCLANG_LIBDIR=${PREFIX}/lib \
    -DBUILD_CUDA_MODULE=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUNDLE_OPEN3D_ML=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_AZURE_KINECT=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_ISPC_MODULE=OFF \
    -DBUILD_GUI=ON \
    -DBUILD_LIBREALSENSE=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_WEBRTC=ON \
    -DENABLE_HEADLESS_RENDERING=OFF \
    -DBUILD_JUPYTER_EXTENSION=ON \
    -DOPEN3D_USE_ONEAPI_PACKAGES=OFF \
    -DUSE_BLAS=ON \
    -DUSE_SYSTEM_ASSIMP=ON \
    -DUSE_SYSTEM_BLAS=ON \
    -DUSE_SYSTEM_CURL=ON \
    -DUSE_SYSTEM_EIGEN3=ON \
    -DUSE_SYSTEM_EMBREE=ON \
    -DUSE_SYSTEM_FMT=ON \
    -DUSE_SYSTEM_GLEW=ON \
    -DUSE_SYSTEM_GLFW=ON \
    -DUSE_SYSTEM_GOOGLETEST=ON \
    -DUSE_SYSTEM_IMGUI=OFF \
    -DUSE_SYSTEM_JPEG=ON \
    -DUSE_SYSTEM_JSONCPP=ON \
    -DUSE_SYSTEM_LIBLZF=ON \
    -DUSE_SYSTEM_LIBREALSENSE=OFF \
    -DUSE_SYSTEM_MSGPACK=ON \
    -DUSE_SYSTEM_NANOFLANN=ON \
    -DUSE_SYSTEM_OPENSSL=ON \
    -DUSE_SYSTEM_PNG=ON \
    -DUSE_SYSTEM_PYBIND11=ON \
    -DUSE_SYSTEM_QHULLCPP=ON \
    -DUSE_SYSTEM_TBB=ON \
    -DUSE_SYSTEM_TINYGLTF=OFF \
    -DUSE_SYSTEM_TINYOBJLOADER=ON \
    -DUSE_SYSTEM_VTK=ON \
    -DCMAKE_DISABLE_FIND_PACKAGE_Viskores=TRUE \
    -DUSE_SYSTEM_ZEROMQ=ON \
    -DWITH_IPP=OFF \
    -DWITH_FAISS=OFF \
    -DPython3_EXECUTABLE=$PYTHON

JOBS=$(( CPU_COUNT > 4 ? CPU_COUNT - 4 : 1 ))
# Use -j1 temporarily to debug build failures, then restore -j${JOBS}
cmake --build . --config Release -- -j${JOBS}
cmake --build . --config Release --target install
cmake --build . --config Release --target install-pip-package
